name: Discord Ticket Proxy - Bug

description: File a bug report which was filed on Discord. Used internally for issue filing and is not expected to be used by other users.

title: "[Ticket Bug]: "

labels: ["bug"]

body:

  - type: input
    id: ticket_number
    attributes:
      label: Discord Ticket Number
      description: What is the ticket number assigned by *Tickets*?
    validations:
      required: true

  - type: input
    id: ticket_user
    attributes:
      label: Discord User
      description: What is the user who created the ticket (Username)?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected
      description: What is it that the user who filed the ticket expected?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: What is it that the user who filed the ticket actually experienced?
    validations:
      required: true