name: Maven Build and Release

on:
  push:
    branches:
      - "**" # Currently set to all branches because of me needing to test the actual code.
            # Will change later when I or James finalise this.
    tags:
      - "v**"

  workflow_dispatch:
    branches: "**"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: Extract Release Notes
        id: release-notes
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/v}  # Strips 'refs/tags/v' from the tag name
          ESCAPED_TAG_NAME=$(echo $TAG_NAME | sed 's/[][*^$.\]/\\&/g')  # Escapes regex characters
          RELEASE_NOTES=$(awk "/^## \\[${ESCAPED_TAG_NAME}\\]/,/^## /{if (!/^## \\[${ESCAPED_TAG_NAME}\\]/ && !/^## /)print}" README.md)
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          echo "notes::$RELEASE_NOTES" >> $GITHUB_OUTPUT

        # Reason for getting rid of "::set:output": GitHub has deprecated "::set:output",
        # see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for more information.

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release-notes.outputs.notes }}